python:
  - 3.7
  - 3.8
  - 3.9

mpi:
  - nompi
  - mpich
  - openmpi

pin_run_as_build:
  mpich:
    min_pin: x.x
    max_pin: x.x

  openmpi:
    min_pin: x.x
    max_pin: x.x

  python:
    min_pin: x.x
    max_pin: x.x
