python:
  - 3.9
  - 3.10

mpi:
  - nompi
  - mpich
  - openmpi
  - hpc

pin_run_as_build:
  mpich:
    min_pin: x.x
    max_pin: x.x

  openmpi:
    min_pin: x.x
    max_pin: x.x

  python:
    min_pin: x.x
    max_pin: x.x
