{% set name = "E3SM-Unified" %}
{% set version = "1.9.0rc10" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `e3sm-unified * mpi_mpich_*` for mpich
  # `e3sm-unified * mpi_*` for any mpi
  # `e3sm-unified * nompi_*` for no mpi

  {% if mpi == 'nompi' or mpi == 'hpc' %}
  {% set mpi_prefix = "nompi" %}
  {% set build_prefix = mpi %}
  {% else %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% set build_prefix = mpi_prefix %}
  {% endif %}
  string: "{{ build_prefix }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python
  run:
    ### main packages ###
    - python
    - chemdyg 0.1.2rc3
    - e3sm_diags 2.9.0rc2
    - e3sm_to_cmip 1.10.0rc1
    - geometric_features 1.2.0
    # fixes an issues with cryptography <37 constraint
    - globus-cli >=3.15.0
    - ilamb 2.6  # [mpi != 'nompi' and mpi != 'hpc']
    - ipython
    - jupyter
    - livvkit 3.0.1
    - mache 1.17.0rc2
    - moab 5.5.0 {{ mpi_prefix }}_tempest_*  # [mpi != 'hpc']
    - mpas-analysis 1.9.0rc3
    - mpas_tools 0.21.0
    - nco 5.1.7  # [mpi != 'hpc']
    - pcmdi_metrics 2.3.1
    - tempest-remap 2.2.0  # [mpi != 'hpc']
    - tempest-extremes 2.2.1 {{ mpi_prefix }}_*  # [mpi != 'hpc']
    - xcdat 0.5.0
    - zppy 2.3.0rc3
    - zstash 1.4.0rc3  # [linux]
    ### dependencies ###
    - {{ mpi }}  # [mpi != 'nompi' and mpi != 'hpc']
    - blas
    - bottleneck
    - cartopy >=0.17.0
    - cdat_info 8.2.1
    - cdms2 3.1.5rc4
    - cdtime 3.1.4
    - cdutil 8.2.1
    - cmocean
    - dask 2023.6.0
    - dogpile.cache
    - eofs
    - esmf 8.4.2 {{ mpi_prefix }}_*  # [mpi != 'hpc']
    - f90nml
    - ffmpeg
    - genutil 8.2.1
    - globus-sdk
    - gsw
    - hdf5 1.14.1 {{ mpi_prefix }}_*
    - ipygany
    - libnetcdf 4.9.2 {{ mpi_prefix }}_*
    - lxml
    - matplotlib
    - metpy
    - mpi4py  # [mpi != 'nompi' and mpi != 'hpc']
    - nb_conda
    - nb_conda_kernels
    - ncview 2.1.8
    - ncvis-climate
    - netcdf4 1.6.4 nompi_*
    - notebook <7.0.0
    - numpy >1.13
    - openssh  # [mpi == 'openmpi']
    - output_viewer 1.3.3
    - pillow
    - plotly
    - progressbar2
    - proj 9.2.1
    - pyevtk
    - pyproj 3.6.0
    - pyremap
    - pytest
    - pywavelets
    - scikit-image
    - scipy >=0.9.0
    - shapely
    - sympy >=0.7.6
    - tabulate
    - xarray 2023.5.0
    - xesmf

    # addition ilamb 2.6 dependencies, for system MPI builds
    - cython
    - cf-units >=2.0.0
    - psutil
    - pandas

test:
  requires:
    - pytest
  imports:
    - chemdyg
    - e3sm_diags
    - e3sm_to_cmip
    - mpas_analysis
    - ILAMB  # [mpi != 'nompi' and mpi != 'hpc']
    - zstash  # [linux]
    - IPython
    - globus_cli
    - livvkit
    - mache
    - zppy
  commands:
    - mpas_analysis --version
    - livv --version
    - e3sm_diags --help
    - zstash --help  # [linux]
    - ilamb-fetch -h  # [mpi != 'nompi' and mpi != 'hpc']
    - ilamb-run -h  # [mpi != 'nompi' and mpi != 'hpc']
    - ilamb-table -h  # [mpi != 'nompi' and mpi != 'hpc']
    - ncks --help  # [mpi != 'hpc']
    - ncap2 --help  # [mpi != 'hpc']
    - jupyter --help
    - jupyter nbextension list
    - ipython -h
    - ipython3 -h
    - globus --help
    - GenerateCSMesh --res 64 --alt --file gravitySam.000000.3d.cubedSphere.g  # [mpi != 'hpc']
    - ESMF_RegridWeightGen --help  # [mpi != 'hpc']
    - test -f ${PREFIX}/bin/Climatology  # [mpi != 'hpc']
    - zppy --help

about:
  home: https://github.com/E3SM-Project/e3sm-unified
  summary: |
    A metapackage for a unified conda environment for analysis of results
    from the Energy Exascale Earth System Model (E3SM).
  dev_url: https://github.com/E3SM-Project/e3sm-unified

extra:
  recipe-maintainers:
    - xylar
