{% set name = "E3SM-Unified" %}
{% set version = "1.5.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `e3sm-unified * mpi_mpich_*` for mpich
  # `e3sm-unified * mpi_*` for any mpi
  # `e3sm-unified * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python
  run:
    ### main packages ###
    - python
    - e3sm_diags 2.5.0
    - e3sm_to_cmip 1.7.1
    - geometric_features 0.5.0
    - globus-cli
    - ilamb 2.6  # [mpi != 'nompi']
    - ipython
    - jupyter
    - livvkit 3.0.0
    - moab 5.3.0
    - mpas-analysis 1.4.0
    - mpas_tools 0.7.0
    - nco 5.0.1
    - processflow 2.2.5  # [linux]
    - tempest-remap 2.1.0
    - tempest-extremes 2.2 {{ mpi_prefix }}_*
    - zstash 1.1.0  # [linux]
    - zppy 1.0.0
    ### dependencies ###
    - {{ mpi }}  # [mpi != 'nompi']
    - blas
    - bottleneck
    - cartopy >=0.17.0
    - cdat_info 8.2.1
    - cdms2 3.1.5
    - cdtime 3.1.4
    - cdutil 8.2.1
    - cmocean
    - dask 2021.5.0
    - eofs
    - esmf 8.1.1 {{ mpi_prefix }}_*
    - f90nml
    - genutil 8.2.1
    - globus-sdk
    - gsw
    - hdf5 1.10.6 {{ mpi_prefix }}_*
    - ipygany
    - libnetcdf 4.8.0 {{ mpi_prefix }}_*
    - lxml
    - matplotlib
    - mpi4py  # [mpi != 'nompi']
    - nb_conda
    - nb_conda_kernels
    - ncview 2.1.8
    - netcdf4 1.5.6 nompi_*
    - numpy >1.13
    - openssh  # [mpi == 'openmpi']
    - output_viewer 1.3.3
    - pillow
    - plotly
    - progressbar2
    - proj 7.2.0
    - pyevtk
    - pyflann
    - pyproj 3.0.1
    - pyremap
    - pytest
    - pywavelets
    - scikit-image
    - scipy >=0.9.0
    - shapely
    - sympy >=0.7.6
    - tabulate
    - xarray 0.18.2
    - xesmf

    # addition ilamb 2.6 dependencies, for system MPI builds
    - cython
    - cf-units >=2.0.0
    - psutil
    - pandas

test:
  requires:
    - pytest
  imports:
    - mpas_analysis
    - acme_diags
    - ILAMB  # [mpi != 'nompi']
    - zstash  # [linux]
    - IPython
    - globus_cli
    - livvkit
    - zppy
  commands:
    - mpas_analysis --version
    - livv --version
    - processflow -v  # [linux]
    - e3sm_diags --help
    - zstash --help  # [linux]
    - ilamb-fetch -h  # [mpi != 'nompi']
    - ilamb-run -h  # [mpi != 'nompi']
    - ilamb-table -h  # [mpi != 'nompi']
    - ncks --help
    - ncap2 --help
    - jupyter --help
    - jupyter nbextension list
    - ipython -h
    - ipython3 -h
    - globus --help
    - GenerateCSMesh --res 64 --alt --file gravitySam.000000.3d.cubedSphere.g
    - ESMF_RegridWeightGen --help
    - test -f ${PREFIX}/bin/Climatology
    - zppy --help

about:
  home: https://github.com/E3SM-Project/e3sm-unified
  summary: |
    A metapackage for a unified conda environment for analysis of results
    from the Energy Exascale Earth System Model (E3SM).
  dev_url: https://github.com/E3SM-Project/e3sm-unified

extra:
  recipe-maintainers:
    - xylar
