{% set name = "E3SM-Unified" %}
{% set version = "1.12.0rc2" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `e3sm-unified * mpi_mpich_*` for mpich
  # `e3sm-unified * mpi_*` for any mpi
  # `e3sm-unified * nompi_*` for no mpi

  {% if mpi == 'nompi' or mpi == 'hpc' %}
  {% set mpi_prefix = "nompi" %}
  {% set build_prefix = mpi %}
  {% else %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% set build_prefix = mpi_prefix %}
  {% endif %}
  string: "{{ build_prefix }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python
  run:
    ### main packages ###
    - python
    - r
    - cdo
    - chemdyg 1.1.1rc1
    - e3sm_diags 3.1.0rc2
    - e3sm_to_cmip 1.13.0rc3
    - e3sm-tools 3.0.2  # [linux]
    - geometric_features 1.6.1
    # fixes an issues with cryptography <37 constraint
    - globus-cli >=3.15.0
    - ilamb 2.7.2  # [mpi != 'nompi' and mpi != 'hpc']
    - ipython
    - jupyter
    - livvkit 3.2.0
    - mache 2.0.0rc2
    - moab 5.5.1 {{ mpi_prefix }}_tempest_*  # [mpi != 'hpc']
    - mosaic 1.2.0
    - mpas-analysis 1.14.0rc2
    - mpas_tools 1.4.0rc1
    - nco 5.3.6  # [mpi != 'hpc']
    - pcmdi_metrics 4.0.1
    - squadgen 1.2.2  # [linux]
    - tempest-remap 2.2.0  # [mpi != 'hpc']
    - tempest-extremes 2.4 {{ mpi_prefix }}_*  # [mpi != 'hpc']
    - uxarray >=2024.12.0
    - xcdat 0.10.1
    - zppy 3.1.0rc3
    - zppy-interfaces 0.2.0rc2
    - zstash 1.5.0rc4  # [linux]

    ### mkdocs
    - mkdocs-material
    - pymdown-extensions
    - mkdocs-monorepo-plugin
    - mdutils
    - mkdocs-bibtex 2.18.0
    - mkdocs-redirects
    - markdownlint-cli2

    ### dependencies ###
    - {{ mpi }}  # [mpi != 'nompi' and mpi != 'hpc']
    - blas
    - bottleneck
    - cartopy >=0.17.0
    - cmocean
    - dask 2025.9.1
    - dogpile.cache
    - eofs
    - esmf 8.9.0 {{ mpi_prefix }}_*
    - esmpy 8.9.0
    - f90nml
    - ffmpeg
    - globus-sdk
    - gsw
    - hdf5 1.14.6 {{ mpi_prefix }}_*
    - ipygany
    - libnetcdf 4.9.3 {{ mpi_prefix }}_*
    - lxml
    - matplotlib-base 3.10.6
    - metpy
    - mpi4py  # [mpi != 'nompi' and mpi != 'hpc']
    - ncview 2.1.8
    - ncvis-climate 2024.01.26
    - nc-time-axis
    - netcdf4 1.7.2 nompi_*
    - notebook
    - numpy >=2.0.0
    - openssh  # [mpi == 'openmpi']
    - output_viewer 1.3.3
    - pillow
    - plotly
    - progressbar2
    - proj 9.6.2
    - pyevtk
    - pyproj 3.7.2
    - pyremap
    - pytest
    - pywavelets
    - r-tidyverse
    - r-dplyr 1.1.4
    - r-ggplot2
    - scikit-image
    - scipy >=0.9.0
    - shapely
    - sympy >=0.7.6
    - tabulate
    - windspharm
    - xarray 2025.9.0
    - xesmf 0.8.8

    # addition ilamb 2.7 dependencies, for system MPI builds
    - cython  # [mpi == 'hpc']
    - cf-units >=2.0.0  # [mpi == 'hpc']
    - psutil  # [mpi == 'hpc']
    - pandas  # [mpi == 'hpc']

test:
  requires:
    - pytest
  imports:
    - chemdyg
    - e3sm_diags
    - e3sm_to_cmip
    - mpas_analysis
    - ILAMB  # [mpi != 'nompi' and mpi != 'hpc']
    - zstash  # [linux]
    - IPython
    - globus_cli
    - livvkit
    - mache
    - zppy
  commands:
    - mpas_analysis --version
    - livv --version
    - e3sm_diags --help
    - zstash --help  # [linux]
    - ilamb-fetch -h  # [mpi != 'nompi' and mpi != 'hpc']
    - ilamb-run -h  # [mpi != 'nompi' and mpi != 'hpc']
    - ncks --help  # [mpi != 'hpc']
    - ncap2 --help  # [mpi != 'hpc']
    - jupyter --help
    - ipython -h
    - ipython3 -h
    - globus --help
    - GenerateCSMesh --res 64 --alt --file gravitySam.000000.3d.cubedSphere.g  # [mpi != 'hpc']
    - ESMF_RegridWeightGen --help  # [mpi != 'hpc']
    - test -f ${PREFIX}/bin/Climatology  # [mpi != 'hpc']
    - zppy --help

about:
  home: https://github.com/E3SM-Project/e3sm-unified
  summary: |
    A metapackage for a unified conda environment for analysis of results
    from the Energy Exascale Earth System Model (E3SM).
  dev_url: https://github.com/E3SM-Project/e3sm-unified

extra:
  recipe-maintainers:
    - xylar
