{% set name = "CIME-env" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
  run:
    ### main packages ###
    - python >=3.7
    # channel: conda-forge
    - evv4esm 0.2.4
    ### dependencies ###
    # channel: conda-forge
    - numpy >1.13
    - scipy
    - pandas
    - matplotlib
test:
  requires:
    - pytest
  imports:
    - evv4esm
  commands:
    - evv --version
about:
  home: https://github.com/E3SM-Project/e3sm-unified
  summary: |
    A metapackage for a conda environment used when running CIME SystemTests with
    the Energy Exascale Earth System Model (E3SM) and can be used on compute nodes.
  dev_url: https://github.com/E3SM-Project/e3sm-unified

extra:
  recipe-maintainers:
    - xylar
    - jhkennedy
